org: renanmelo
service: foodiary-api

provider:
    name: aws
    runtime: nodejs22.x
    region: sa-east-1
    memorySize: 128

package:
    individually: true

build:
    esbuild:
        configFile: ./esbuild.config.mjs

functions:
    hello:
        handler: src/main/functions/hello.handler
        events:
            - httpApi:
                  path: /hello
                  method: POST
