org: renanmelo
service: foodiary-api

provider:
    name: aws
    runtime: nodejs22.x
    region: sa-east-1
    memorySize: 128
    stage: ${opt:stage, 'dev'}
    environment: ${file(./sls/config/env.yml)}
    iam:
        role: ${file(./sls/config/role.yml)}
    httpApi:
        authorizers:
            CognitoAuthorizer:
                type: jwt
                identitySource: $request.header.Authorization
                issuerUrl: !GetAtt UserPool.ProviderURL
                audience:
                    - !Ref UserPoolClient

package:
    individually: true

custom:
    cognito:
        PoolName: ${self:service}-${self:provider.stage}-UserPool

build:
    esbuild:
        configFile: ./esbuild.config.mjs

functions:
    - ${file(./sls/functions/auth.yml)}
    - ${file(./sls/functions/meal.yml)}
    - ${file(./sls/functions/account.yml)}
    - ${file(./sls/functions/profile.yml)}
    - ${file(./sls/functions/goal.yml)}

resources:
    - ${file(./sls/resources/UserPool.yml)}
    - ${file(./sls/resources/MainTable.yml)}
    - ${file(./sls/resources/MealsBucket.yml)}
    - ${file(./sls/resources/MealsBucketCDN.yml)}
    - ${file(./sls/resources/MealsQueue.yml)}
    - ${file(./sls/resources/DLQAlarmsTopic.yml)}
