export enum ErrorCode {
    VALIDATION = "VALIDATION",
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    //HTTP
    BAD_REQUEST = "BAD_REQUEST",
    INTERNAL_ERROR = "INTERNAL_ERROR",
}
