statements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource:
        - !GetAtt MainTable.Arn
        - !Sub '${MainTable.Arn}/index/*'
    - Effect: Allow
      Action: cogniot-idp: AdminDeleteUser
      Resource:
        - !GetAtt UserPool.Arn
